function showNotes(a){var b="";a=registration_charges[a];a[6]?(1==a[0]&&(b+="<li>Participation fee for single member : <b>Rs "+a[3]+"/-</b></li>"),b+="<li>Minimum team members : <b>"+a[5]+"</b></li>",b+="<li>Maximum team members : <b>"+a[1]+"</b></li>",b+="<li>Participation fee for a team : <b>Rs "+a[6]+"/-</b></li>"):(a[0]!=a[1]&&(b+="<li>Maximum participants : <b>"+a[1]+"</b></li>"),b+="<li>Participation fee for "+(1==a[2]?"single":a[2])+" member"+(1<a[2]?"s":"")+" is <b>Rs "+a[3]+"/-</b></li>",
a[4]&&(b+="<li>For each additional member <b>Rs "+a[4]+"</b> per head will be charged.</li>"));$("#notes").html(b?b:"")}
function validateInputes(){var a,b={Email:[],Mobile:[]},f=$("input[name], select[name]");for(a=0;a<f.length;a++){var d=$(f[a]).prop("placeholder"),c=$(f[a]).val(),e=$(f[a]).parent().attr("member_no");member=1==e?"Leader":e+(2==e?"nd":3==e?"rd":"th")+" member";if(("Email"==d||"Mobile"==d)&&0<=b[d].indexOf(c))return alert('You have used '+ d + ' "'+ c +'" more than one time in this form.'),!1;if("Name"==d&!c)return alert(member+"'s name can't be empty."),!1;if("Branch"==d&!c)return alert(member+"'s branch can't be empty."),!1;if("College"==
d&!c)return alert(member+"'s college name can't be empty."),!1;if("Mobile"==d&(c.length!=10 || !c.match(/[7-9][\d]{9}/)))return alert(member+"'s mobile number seems invalid."),!1;if("Email"==d&!c.match(/(.+)\@(.+)\.(.+)/))return alert(member+"'s email address seems invalid."),!1;"Email"!=d&&"Mobile"!=d||b[d].push(c)}}
function updateAvailableButtons(){var a=$("#event").val();if(!a||"none"==a)return!1;$("div.member_detail[member_no]").length>=registration_charges[a][1]?($("#add_member").hide(),$("#submit_form").css("width","300px")):($("#add_member").show(),$("#submit_form").css("width","148px"))}
$(function(){$("#add_member, #submit_form, .member_detail, .note").css("display","none");competitions.sort(function(a,b){var c=a.category.toUpperCase(),e=b.category.toUpperCase();return 1*(c<e?-1:c>e?1:0)});var a="",b;for(b in competitions)a!=competitions[b].category&&(a=competitions[b].category,$('[id="categories"]').append('<option value="'+a.toUpperCase().replace(/\ |\-/gi,"_")+'">'+(competitions[b].sub_category ? (competitions[b].sub_category+' - ') : '')+competitions[b].category+"</option>"));competitions.sort(function(a,b){var c=a.name.toUpperCase(),e=b.name.toUpperCase();
return 1*(c<e?-1:c>e?1:0)});$("#categories").on("change",function(){$("div.member_detail[member_no]").each(function(){1<$(this).attr("member_no")&&$(this).remove()});$("#event").html('<option value="none">Select Event</option>');$("#add_member, #submit_form, .member_detail, .note").css("display","none");updateAvailableButtons();for(var a in competitions)$(this).val()==competitions[a].category.toUpperCase().replace(/\ |\-/gi,"_")&&$('[name="event"]').append('<option value="'+competitions[a].name.replace(/\ |\-/gi,
"_").toUpperCase()+'">'+competitions[a].name+"</option>")});$("#event").on("change",function(){var a=$(this).val();window.location.hash=($("#categories").val()+":"+a).toLowerCase();$(".member_detail, .note").css("display",a&&"none"!=a?"block":"none");$("#add_member, #submit_form").css("display",a&&"none"!=a?"inline-block":"none");$("div.member_detail[member_no]").each(function(){$(this).attr("member_no")>registration_charges[a][0]&&$(this).remove()});for(var b=registration_charges[a][0]-$("div.member_detail[member_no]").length,
c=1;c<=b;c++)$("#add_member").trigger("click");updateAvailableButtons();showNotes(a.toUpperCase())});$("#add_member").click(function(){var a=$("#event").val();if(!a||"none"==a)return!1;a=$(".member_detail").length+1;$(this).before('<div class="member_detail" member_no="'+a+'"><div user_type="member">'+(a+(2==a?"nd":3==a?"rd":"th"))+' Member\'s Detail</div><input placeholder="Name" type="text" name="name[]" required title="Enter your full name as on your collage identity card." /><input placeholder="Email" type="email" name="email[]" required title="Enter your valid email address for further communications." /><input placeholder="Mobile" type="text" pattern="[0-9]{10}" name="mobile[]" required title="Please enter 10 digit mobile number." /><input placeholder="Branch" type="text" name="branch[]" required title="Please enter your branch." /><input placeholder="College" type="text" name="college[]" required title="Enter your current collage name." /></div>');
updateAvailableButtons()});if(a=window.location.hash.match(/\#(.+)\:(.+)/))$("#categories").val(a[1].toUpperCase()).change(),$("#event").val(a[2].toUpperCase()).change()});